# Generated by Django 5.0.6 on 2024-11-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollnum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('rollnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendancemark.student')),
            ],
        ),
    ]
